### PR TITLE
add a echo func that could be use in {% %} 

### PR DESCRIPTION
**Pull request by cuiweixie**

### CODE REVIEW

**Comment by bungle** [comment]
@cuiweixie, thank you! I need to think about this a little bit because I do think that it would be better if it just worked with the normal output functions, but I'm not sure if there is easy way around it. But lets keep this open for now.

**Comment by bungle** [comment]
@cuiweixie, What do you think, should we also have function that does automatic HTML escaping?

**Comment by cuiweixie** [comment]
like template.escape func? why not use template.escape?

**Comment by bungle** [comment]
@cuiweixie, I am preparing for `2.0` release, so I think we can include this now.

**Pull request merged**
